name: Android CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '**/.gitignore'
      - '*.md'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**/.gitignore'
      - '*.md'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

