name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.22.x'

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: |
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_SYSTEM_NAME=Android \
          -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
          -DCMAKE_SYSTEM_VERSION=21 \
          -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang

    - name: Build
      working-directory: ./build
      run: cmake --build .

    - name: Find Library
      run: |
        echo "Finding library location..."
        find . -name "*.so" -type f

    - name: Package Release
      run: |
        mkdir -p release-artifacts
        # Copy source code
        cp -r * release-artifacts/ || true
        # Remove build directory from artifacts to save space
        rm -rf release-artifacts/build
        # Copy built .so files
        find . -name "*.so" -type f -exec cp {} release-artifacts/ \;
        # Create zip with everything
        cd release-artifacts && zip -r GTInternal-${{ github.ref_name }}-full.zip *

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-artifacts/GTInternal-${{ github.ref_name }}-full.zip
          release-artifacts/*.so
        draft: false
        prerelease: false
        generate_release_notes: true
        name: Release ${{ github.ref_name }}
        body: |
          ## GTInternal Android Release ${{ github.ref_name }}
          
          ### Files
          - `GTInternal-${{ github.ref_name }}-full.zip`: Complete package with source code and built files
          - `.so` file: Compiled library only
          
          ### Installation
          1. Download the `.so` file or extract it from the full package
          2. Place it in the appropriate directory on your device
          
          ### Development
          For development, download the `GTInternal-${{ github.ref_name }}-full.zip` which includes:
          - Full source code
          - Built libraries
          - CMake configuration
          - All project files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
